'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cookie.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _120px_Ancient_Great_Ball_Glamour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_120px_Ancient_Great_Ball_Glamour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _120px_Ancient_Ultra_Ball_Glamour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_120px_Ancient_Ultra_Ball_Glamour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _120px_Beast_Ball_Glamour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_120px_Beast_Ball_Glamour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2013_10_18_171438_6561496_2841195642() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2013_10_18_171438_6561496_2841195642", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _635556544299235574_2991773832() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("635556544299235574-2991773832", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _635556544299235574_2991773832_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("635556544299235574-2991773832 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ancient_Poke_Ball_Glamour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ancient_Poke_Ball_Glamour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cookie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cookie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Ball_Artwork_3019201630() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Ball_Artwork-3019201630", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property il_1588xN_2703917927_5dpc_295111173() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("il_1588xN.2703917927_5dpc-295111173", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property master_ball_by_falco4077_d75ae5m_3429987528() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_ball_by_falco4077-d75ae5m-3429987528", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PokeClicker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PokeClicker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pokemon_pokeball_toy_7cm_3996445687() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pokemon-pokeball-toy-7cm-3996445687", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purepng_com_pokeballpokeballdevicepokemon_ballpokemon_capture_ball_17015278258769okdi_3871205728() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purepng.com-pokeballpokeballdevicepokemon-ballpokemon-capture-ball-17015278258769"& _ 
                        "okdi-3871205728", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purepng1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purepng1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th_2510880536() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th-2510880536", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
